apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-config
  labels:
    app: kafka-producer
data:
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap:9094
  PRODUCER_TICK_FREQUENCY: "2000"
