apiVersion: v1
data:
  database-name: YXBpY3VyaW9kYg==
  database-password: YXBpY3VyaW9kYg==
  database-user: YXBpY3VyaW9kYg==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: 58a9fca6-f2d9-4bf3-aa9c-3ed15b51784e
  name: apicuriodb
  namespace: apicurio
type: Opaque
