apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafkatopic
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kafka-topic
    repoURL: https://<git_url>.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
