kind: KafkaUser
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: quarkus-producer
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka-dev
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: event
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: event
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: event
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: topic
          name: event-sr
          patternType: literal
        operation: Describe
        host: '*'       
      - resource:
          type: topic
          name: event-sr
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: event-sr
          patternType: literal
        operation: Create
        host: '*'      
